services:
  redis-master:
    image: bitnami/redis:8.0.3
    container_name: redis-master
    ports:
      - "6379:6379"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - TZ= Asia/Taipei
    volumes:
      - redis-master-data:/bitnami/redis/data
      - ./config/redis-master.conf:/usr/local/etc/redis/redis.conf
    networks:
      - redis-network
    restart: unless-stopped
    command: ["redis-server","/usr/local/etc/redis/redis.conf"]

  redis-replica-1:
    image: bitnami/redis:8.0.3
    container_name: redis-replica-1
    ports:
      - "6380:6379"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - TZ= Asia/Taipei
    volumes:
      - redis-replica-1-data:/bitnami/redis/data
      - ./config/redis-replica.conf:/usr/local/etc/redis/redis.conf
    networks:
      - redis-network
    depends_on:
      - redis-master
    restart: unless-stopped
    command: ["redis-server","/usr/local/etc/redis/redis.conf"]
  redis-replica-2:
    image: bitnami/redis:8.0.3
    container_name: redis-replica-2
    ports:
      - "6381:6379"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - TZ= Asia/Taipei
    volumes:
      - redis-replica-2-data:/bitnami/redis/data
      - ./config/redis-replica.conf:/usr/local/etc/redis/redis.conf
    networks:
      - redis-network
    depends_on:
      - redis-master
    restart: unless-stopped
    command: ["redis-server","/usr/local/etc/redis/redis.conf"]
volumes:
  redis-master-data:
  redis-replica-1-data:
  redis-replica-2-data:
networks:
  redis-network:
    driver: bridge
